### PR TITLE
If emitter.off provides only the event, remove all listeners for that event.

### PR DESCRIPTION
**Pull request by sealice**
This solves the #123 issue.
```
		off<T = any>(type: EventType, handler?: Handler<T>) {
			const handlers = all.get(type);
			if (handlers) {
		            if(handler){
				handlers.splice(handlers.indexOf(handler) >>> 0, 1);
		            } else {
		                all.delete(type);
		            }
			}
		},
```

### CODE REVIEW

**Comment by andreyrd** [comment]
Looks like this needs some formatting fixes and it should be good to go!
I just ran into a bug in my own project, I was using this as a mostly drop in replacement for a Vue-based bus, and it assumes everywhere that all event listeners are removed when the function handle is left out.

**Comment by sealice** [comment]
@andreyrd Thanks, I am going to fix the format.

**Comment by redfox05** [comment]
Quick note, could this be adjusted to allow for partial matching? So we can remove listeners written in a namespaced format.

event.off('myComponent1.addMenuItem')

Which could then be used to remove all listeners for a component on destroy, rather than listing each one, potentially missing some. I'm happy to add the code myself if needed in another PR.

**Comment by sealice** [comment]
> Quick note, could this be adjusted to allow for partial/wildcard matching? So we can remove listeners written in a namespaced format.
> 
> `event.off('myComponent1.addMenuItem')`
> 
> Which could then be used to remove all listeners for a component on destroy, rather than listing each one, potentially missing some. I'm happy to add the code myself if needed in another PR.

This is a good idea, you are welcome to submit your own ideas.

**Comment by workforbala** [comment]
what happened to this PR awaiting for this feature

**Comment by mariusa** [comment]
@developit ping & thanks

**Comment by developit** [comment]
This will be released as 3.0.0.

**Pull request merged**
