### PR TITLE
Add generic types and update tests

### PR DESCRIPTION
**Pull request by jackfranklin**
* Add generic types to `on`, `off` and `emit` to enable some nicer TS
  usage if you specify what type you're expecting from the `EventData`.
* Move the tests to be TypeScript source. This will help catch errors in
  the tests if there are any type errors.
* Create a new test to test the generic types and make sure they pass
  and error when expected.
* Upgrade to Mocha 8.
* Did some tidying up of the package.json scripts.

### CODE REVIEW

**Comment by jackfranklin** [comment]
@developit LMK what you think, thanks!

**Comment by jackfranklin** [comment]
@developit let me know if I can help do anything to help this ship, thanks!

**Comment by developit** [comment]
Will get to this today!

**Comment by developit** [comment]
Ah also some sneaky TS errors in the CI output. I think I have a fix in Codespaces, will check tomorrow morning.

**Comment by developit** [comment]
Shipped as [2.1.0](https://github.com/developit/mitt/releases/tag/2.1.0), no longer a preview release :)

**Pull request merged**
