### PR TITLE
Cleanup Build Chain

### PR DESCRIPTION
**Pull request by lukeed**
* Made use of Rollup's [multiple targets](https://github.com/rollup/rollup/wiki/Command-Line-Interface#targets)
* Add a `module` entry (`dist/mitt.es.js`)
* No need to `mkdirp dist` before build

### CODE REVIEW

**Comment by developit** [comment]
Any size difference? I had thought we were outputting it, but I don't see a line in the travis log.

**Comment by lukeed** [comment]
Same size, 186. It's the same builds just using more api setup and less cli

**Comment by developit** [comment]
Awesome. Just going to run a diff of the `dist` before and after to make sure the UMD entrypoint didn't change.

**Comment by lukeed** [comment]
It's the same. Diff'd locally, only `.es.js` are different (because new).

**Pull request merged**
