### PR TITLE
Fixing TypeScript usage. Fixes #60

### LINKED ISSUE #60: Uncaught TypeError: mitt is not a constructor
Hi!
Im trying to use mitt in our react project using typescript.
But I get this error in runtime: 

```
Uncaught TypeError: mitt is not a constructor
    at eval (api.ts:11)
    at Object../packages/foo-api/api.ts (bundle.js:10804)
    at __webpack_require__ (bundle.js:672)
    at fn (foo.js:98)
    at eval (index.ts:5)
    at Object../packages/foo-api/index.ts (bundle.js:10817)
    at __webpack_require__ (bundle.js:672)
    at fn (bundle.js:98)
    at eval (Foo.view.tsx:15)
    at Object../packages/foo-ui/Foo.view.tsx (bundle.js:11779)

```

I'm using ut just like in your example
```
import * as mitt from 'mitt'
const emitter: mitt.Emitter = new mitt()
```

When debugging in Dev tools and check mitt it's an object, not a contructor.
```
Object {__esModule: true, default: function}
   default: function mitt(all )
   __esModule: true
   __proto__: Object
```

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by davidkpiano**
Since `mitt` is just a function, we can (and should) declare it as such. This small change avoids the need for workarounds mentioned in #60 and also makes the code usage in TypeScript simpler, by treating `mitt` as a function instead of as a constructor.

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
This is still not correct, you have to `export default`

**Comment by davidkpiano** [comment]
> This is still not correct, you have to `export default`

How is it not correct? I tried it and it worked.

**Comment by developit** [comment]
This seems correct to me - it's a factory, not a constructor. What was the export change @ForsakenHarmony?

**Comment by ForsakenHarmony** [comment]
Maybe something didn't update in time for me, but I tired it with these changes and still had to use `import * as mitt from mitt`

then I changed `export = mitt;` to `export default mitt;` and that worked

**Comment by ForsakenHarmony** [comment]
it still happens to me with webstorm, I have to change it to `export default` otherwise it shows a typescript error

**Comment by anru** [comment]
hi @davidkpiano , thanks for PR! I've merged it in my fork under  [emitt](https://www.npmjs.com/package/emitt) package

**Comment by Jack-Works** [comment]
Hello? I see in the release log it said `You can now invoke mitt() with or without new in TypeScript (#60/#67 - thanks @​davidkpiano)`

But when the bot upgrade my code, it reports error in CI
```
error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

20     private eventEmitter = new mitt()
 ```

See: https://circleci.com/gh/DimensionDev/Holoflows-Kit/348

Is this change by-design or a mistake?

**Pull request merged**
