### PR TITLE
Cleanup

### LINKED ISSUE #38: Clean up repo root
- [x] Auto-generate (and gitignore) `typings.json` during build via [package-to-typings](https://www.npmjs.com/package/package-to-typings)
- [x] move `mitt.d.ts` into `src/` (it's still included in the npm package)
- [x] Move `.babelrc` into `tests/` since that's the only place it's used
- [x] gitignore `yarn.lock`
- [x] remove `example.js` (started in #37 - should be in the readme instead)

/cc @tunnckoCore

### PR DESCRIPTION
**Pull request by tunnckoCore**
fix #38 

Just can't get the idea of these typings and etc stuff. :D Too much for me. Is it really needed to integrate `package-to-typings`? Isn't enough to just point to the `src/mitt.d.ts`?

### CODE REVIEW

**Comment by developit** [comment]
@tunnckoCore I tried looking around to see if there was a way to specify the information from `typings.json` in the `package.json`, but I couldn't find anything.  I actually have no idea what `typings.json` is for, haha.

**Comment by tunnckoCore** [comment]
> I actually have no idea what typings.json is for, haha.

ahah, great to hear that! :rofl: So we can stick to that typings.json then? aaaand erm.. seen that there is typings field in packages.. so.. they are probably enough, huh? :D

**Comment by developit** [comment]
Library has been rewritten in TS.

**Comment by tunnckoCore** [comment]
Awesome! <3 :)

**Pull request closed without merging**
