### PR TITLE
Add clear() function

### PR DESCRIPTION
**Pull request by jaylinski**
### Description 

Adds a `clear()` function, as discussed in https://github.com/developit/mitt/pull/72#issuecomment-361379479.

As noted in https://github.com/developit/mitt/pull/72#issuecomment-422786692, implementing a "clear all events"-functionality via `off()` can be problematic, since events passed in the mitt `all`-param will get removed.   
The `clear()`-method is more expressive in what it does.

Is an alternative to #105.

### Is `Map.clear()` supported by all major browsers?

Yes. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear

### Relates to

#70 #72 #102

### CODE REVIEW

**Comment by jaylinski** [comment]
> Error: compressed-size-action was unable to comment on your PR.
This can happen for PR's originating from a fork without write permissions.
You can copy the size table directly into a comment using the markdown below:


**Size Change:** +51 B (5%) 🔍

**Total Size:** 981 B

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `dist/mitt.es.js` | 227 B | +14 B (6%) | 🔍 |
| `dist/mitt.js` | 227 B | +14 B (6%) | 🔍 |
| `dist/mitt.modern.js` | 222 B | +10 B (4%) |  |
| `dist/mitt.umd.js` | 305 B | +13 B (4%) |  |

**Comment by developit** [comment]
I think I prefer this version, but I'm thinking of ways to offset the size impact.

**Comment by jaylinski** [comment]
Regarding size: the only thing I can think of would be to shorten the name from `clear` to `rm` (for remove). This is the minified string: `,clear:function(){n.clear()}`

This is the size output when I run `npm run build`:
```
Build "mitt" to dist:
        198 B: mitt.js.gz
        189 B: mitt.js.br
        191 B: mitt.modern.js.gz
        164 B: mitt.modern.js.br
        196 B: mitt.es.js.gz
        191 B: mitt.es.js.br
        276 B: mitt.umd.js.gz
        234 B: mitt.umd.js.br
```
So still below 200 B on modern gz. :)

**Comment by jaylinski** [comment]
@developit Is there any chance you will merge and tag this in the next week or so?

(Otherwise I'll create my own fork in the meantime.)

**Comment by developit** [comment]
@jaylinski would you be okay if we merged the `.all` version instead? (your #105)

**Comment by jaylinski** [comment]
> @jaylinski would you be okay if we merged the `.all` version instead? (your #105)

Yes, would be okay for me.

**Comment by developit** [comment]
closing now that #105 is merged!

**Pull request closed without merging**
