### PR TITLE
Improved type definitions to allow event typings

### PR DESCRIPTION
**Pull request by deskoh**
Backwards-compatible enhancements for #78.

```ts
// Event typings can be provided through module augmentation:
declare module 'mitt' {
  interface EventTypes {
    foo: { bar: string }
  }
}

// EventTypes not provided: No type errors;
// EventTypes provided: Type check error: Property 'baz' does not exist on type '{ bar: string; }'
emitter.on('foo', e => console.log(e.baz));
// EventTypes provided: No type errors, `bar` is of type `string`
emitter.on('foo', e => console.log(e.bar));

// EventTypes not provided: No type errors;
// EventTypes provided: Type check error: Type 'number' is not assignable to type 'string'.
emitter.emit('foo', { bar: 1 });
// EventTypes provided: No type errors, `bar` is of type `string`
emitter.emit('foo', { bar: 'data' });

function onFoo(event: { bar: string }) {}
function onFoo2(event: { baz: string }) {}

// EventTypes not provided: No type errors;
// EventTypes not provided: Type check error: Property 'baz' is missing in type '{ bar: string; }' but required in type '{ baz: string; }'
emitter.off('foo', onFoo2);
// EventTypes provided: No type errors
emitter.off('foo', onFoo);
```

### CODE REVIEW

**Comment by developit** [comment]
We'll need to check if this is still necessary now that #99 is merged and Mitt is written in TypeScript.

**Comment by deskoh** [comment]
@developit Updated PR for TypeScript

**Comment by developit** [comment]
@deskoh I think this might need to be tweaked because `all` is now a `Map`?

**Comment by deskoh** [comment]
This PR differs from the goals of #89 which could allow such usage:

```ts
// Typings for 'foo' event is defined twice, and not guaranteed to be consistent, but with no typings error
emitter.on<string>('foo', (x: string) => {})
emitter.emit<int>('foo', (x: int) => {})
```

This PR proposed usage is:

```ts
// Define event `foo` with specific event handler type
declare module 'mitt' {
  interface EventTypes {
    foo: { bar: string }
  }
}
emitter.on('foo', (x: string) => {})

// Typings error
emitter.emit('foo', (x: int) => {})
```

Furthermore, with[Module Augmentation / Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html),  `EventTypes` can be defined across different files where subscribers are defined.

Let me know what you think.

**Comment by benhjames** [comment]
This is really cool! The only question I have is around this PR being a breaking change. Providing the generics on the methods themselves no longer seems to work, as can be seen in the breaking test in the GitHub actions build:

```ts
const badHandler = (x: number) => {};
const goodHandler = (x: string) => {};

// @ts-expect-error
emitter.on<string>('foo', badHandler);
emitter.on<string>('foo', goodHandler);
```

TS no longer emits an error for this first usage, so consumers would need to update to some other way of enforcing type safety like `mitt<{ foo: string }>()` instead (which I would say is a superior option, but breaking nevertheless)

**Comment by developit** [comment]
Hiya @deskoh - I really appreciate the PR and your patience as I took forever to review. I've merged #114, which was a TS implementation of roughly what you had here. Cheers!

**Pull request closed without merging**
