### PR TITLE
chore(editorconfig): add editorconfig

### PR DESCRIPTION
**Pull request by floriangosse**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
you cant add what you want. @developit has  preferences, and for #19 i was kinda forced to add editorconfig, so i added editorconfig that he want and thought to add :)

**Comment by developit** [comment]
Hmm - here I thought I was being clever using Github's web interface to edit, and it basically overwrote yours. Hopefully that's not annoying, sorry!

What you had was pretty close to what I usually use, just with some defaults moved around and a character set specified for JavaScript.  The source for what I ammended is [preact's editorconfig](https://github.com/developit/preact/blob/master/.editorconfig).

**Comment by floriangosse** [comment]
Everything okay. :smile:

I didn't know about the preact's editorconfig. But it makes sense to reuse the config.

**Comment by developit** [comment]
Cool! Time to merge then :)

**Pull request merged**
