### PR TITLE
Add Size Limit

### PR DESCRIPTION
**Pull request by ai**
@developit  It is so awesome how small is `mitt`. And it is great that you take care about size.

I bring you [Size Limt](https://github.com/ai/size-limit), the special tool for npm library size control.

I created it for [nanoid](https://github.com/ai/nanoid) and [nanoevents](https://github.com/ai/nanoevents). Right now Autoprefixer, Browserslist, PostCSS, MobX and Material-UI use it.

What benefits it will bring to `mitt`:

1. It is more accurate. Instead of checking file size, it calculates the real cost for end-user. To be really specific, Size Limit creates an empty webpack project in memory. Then, it adds your library as a dependency to the project and calculates the real cost of your libraries, including all dependencies, webpack’s polyfills for `process`, etc.
2. It prevents size regression. I added `size-limit` call to `npm test`. So if somebody will accidentally increase the size (for example, by using `global`), Size Limit will tell you about it on Travis CI.

Here is good article with more details: https://evilmartians.com/chronicles/size-limit-make-the-web-lighter

### CODE REVIEW

**Comment by charlike** [comment]
I don't really like it, but @developit should decide :)

Actually, i'm just not sure if it counts the Webpack's wrapper or not. If not, then okey, i may consider adding it in my projects too, including [dush](https://github.com/charlike/dush)

**Comment by ai** [comment]
@charlike I understand that webpack looks to the hard solution :).

But most of the users use it (and browserify or rollup have same problems with inserting `process` polyfills).

For my experience, it is the best way to calculate the real cost for most of the users. You can think about it as completely synthetic vs more real benchmark.

**Comment by thiamsantos** [comment]
I never completely understand the difference, but [bundlesize](https://github.com/siddharthkp/bundlesize) can be an alternative for size-limit.

**Comment by ai** [comment]
@thiamsantos yeap, `bundlesize` will prevent with size regression too.

But `bundlesize` is not so accurate. It shows only file size and don’t calculate the real cost for users. So it is more like a very synthetic benchmark.

In this article Barnov showed the difference between Size Limit and bundlesize and why the real cost is more important:
https://evilmartians.com/chronicles/size-limit-make-the-web-lighter

**Comment by thiamsantos** [comment]
> In this article Barnov showed the difference between Size Limit and bundlesize and why the real cost is more important:
https://evilmartians.com/chronicles/size-limit-make-the-web-lighter

Awesome article! Now the difference makes sense. Thanks! Congratulations for the incredible work.

**Comment by charlike** [comment]
One more thing why i don't like such tools is that i just always believe on the filesystem and nothing more. I care for my code and almost always the count includes the umd wrapper. If not umd wrapper than Webpack's which is a bit more bigger probably, but i don't care it isn't big diff.

I'm trying `size-limit` not in minimal package: Rollup, no deps, babel-preset-env with "last 2 versions", no specific globals or such things, and uglify es. Final result is `645b` for the `.gz` file, where size-limit shows it is `570b`. It's totally impossible :rofl: Probably different compression? Looking over deps, i assume it is same - `gzip`.

**Comment by ai** [comment]
@charlike here is a good article why `bundlesize` way could be wrong. Most of the optimization I did with bundle size in my projects was not shown by `bundlesize`.
https://evilmartians.com/chronicles/size-limit-make-the-web-lighter

Remember when in the past we optimize websites based on just CSS+JS+images size. Now we understand that there are many problems (like latency) and we use much better benchmarks.

Can you show the project? I will tell you the reason of different size. I think it could happen because of the way how webpack bundled dependencies.

**Comment by charlike** [comment]
I know how webpack bundle looks like and that's why I think it is impossible, but anyway ;d

I will show you when upload it to github.

**Comment by ai** [comment]
@charlike I made example with `mitt`

[Empty project](https://github.com/ai/size-limit-example): 290 bytes
[After `mitt` was added](https://github.com/ai/size-limit-example/tree/mitt): 416 bytes
Diff: 126 bytes
Current scripts or bundlesize: 183 bytes

We have this difference because webpack bundle already have the preamble. Gzip combines repeated parts from library and preamble.

Not the there is no such thing as `dist/mitt.js` in client’s world. The client will see only their bundle size. And Size Limit result is much closer to client reality.

**Comment by ai** [comment]
I got a good example, why taking webpack size is much more accurate. [`nanobus`](https://github.com/choojs/nanobus) event emitter is very small too (to is created for `choo` project created to be compact).

It is about 1KB size. But when end-user will add `nanobus` to their projects, user’s bundles will be increased to 5KB. Because `nanobus` call `require('assert')` (it is Node’s built-in library, but Webpack inserts 4K polyfill for it).

What size is more real? `bundlesize`’s 1 KB or `size-limit`’s 5 KB?

Same mistake we found in `emoji-mart` and reduced its size by 20%. In `logux-client` I saved 90% of size (because of unexpected big 100 KB dependency for simple ID generation). In `nanoid` I saved 33% because of `global` instead of `window` (webpack inserts polyfill here too). In Browserslist we reduced the size by 25% because we found unnecessary imports from `caniuse-lite`. All these mistakes will not be found by `bundlesize`.

I agree that these dependencies problems are not so actual for `mitt` (since it has no dependencies). But what if somebody will add `global` in next commit. Or right now we see that module size is bigger for webpack.

**Comment by charlike** [comment]
> What size is more real? bundlesize’s 1 KB or size-limit’s 5 KB?

Yes, Bundlesize's :) Most modules by Yosh & co (devs around him) are using massively `assert` and user/end-user **must** use unassertify tool when will build for browser. They use it totally intentional, because it can be removed for production and they do everything that way.

So, no, not good example :)

For the rest of what you talking i'm agree. It can be helpful sometimes.

**Comment by ai** [comment]
@charlike you know that users don’t read docs. I pretty sure most of `choo` users have `assert` inside ;).

Good API when it is more easy to do right think rather than wrong thing. When you must read docs and add extra loader — in this case add `nanobus` correctly is more complicated rather than add it in wrong way. As result, many users will make mistake.

But yeap, this thread is not about `nanobus` :D

**Comment by charlike** [comment]
> you know that users don’t read docs.

But should, because everyone of us put significant amount of time on that. God, if no one read, why we have README shown on each repo page :D

> I pretty sure most of choo users have assert inside ;).

Me too :D

**Comment by developit** [comment]
I actually think the delta idea is really neat!

**Pull request closed without merging**
