### PR TITLE
chore: fix typescript issue with `NodeNext`, fix #166

### LINKED ISSUE #166: Typescript issue with `moduleResolution: NodeNext`
Typescript cannot find types for mitt when targeting esm while declaring `moduleResolution: NodeNext`.

```ts
import mitt from 'mitt';
// or 
import { default as mitt } from 'mitt';
```

Getting

```
error TS7016: Could not find a declaration file for module 'mitt'. '/home/mister-hope/projects/vuepress-theme-hope/node_modules/.pnpm/mitt@3.0.0/node_modules/mitt/dist/mitt.mjs' implicitly has an 'any' type.
```

The problem is that the export field is missing declaration file, also the project is not outputing a `index.d.mts` for `index.mjs`.

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by lbm98** [comment]
We might also need to lower the "typings" property as described in [typescriptlang.org](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing)

```diff
diff --git a/node_modules/mitt/package.json b/node_modules/mitt/package.json
index ad38c7b..7649cc8 100644
--- a/node_modules/mitt/package.json
+++ b/node_modules/mitt/package.json
@@ -7,12 +7,13 @@
   "jsnext:main": "dist/mitt.mjs",
   "umd:main": "dist/mitt.umd.js",
   "source": "src/index.ts",
-  "typings": "index.d.ts",
   "exports": {
+    "types": "./index.d.ts",
     "import": "./dist/mitt.mjs",
     "require": "./dist/mitt.js",
     "default": "./dist/mitt.mjs"
   },
+  "typings": "index.d.ts",
   "scripts": {
     "test": "npm-run-all --silent typecheck lint mocha test-types",
     "mocha": "mocha test",
```

**Comment by Mister-Hope** [comment]
I did not remove `typings` field? Why are you mentioning that?

**Comment by Mister-Hope** [comment]
Hi, any update with this?

**Comment by Mister-Hope** [comment]
Any update with this?

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Thanks! Sorry about the delay.

**Comment by Mister-Hope** [comment]
Any release schedule for this?

**Comment by Mister-Hope** [comment]
Hi bro, we still need this fix to be published as 3.0.1

**Comment by marcoreni** [comment]
hey @developit , is there a way to get this released?

**Comment by dgeibi** [comment]
Hi @developit, we need v3.0.1

**Pull request merged**
