### PR TITLE
Fix `emit` argument annotation

### PR DESCRIPTION
**Pull request by rvikmanis**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
i believe yea

**Comment by developit** [comment]
I wonder if it should be marked as optional? (is that a thing?)

**Comment by tunnckoCore** [comment]
Don't know, don't understand them. If @rvikmanis know let change it, otherwise will just hit the button.

**Comment by developit** [comment]
Can do it later.

**Comment by rvikmanis** [comment]
Marking it optional won't have much of a practical difference, because of the way flow treats `any`, but I'd still do it just to make clear the intention.

**Comment by tunnckoCore** [comment]
That's why I hate types and typings, at least until they get native. They lead to more mess than better collaboration between devs - all this build time tool chains and etc, that whole thing around "modern javascript" really sucks, reminds me one article that I read before few weeks or so: "JavaScript is no more _'write and run'_ lang".

**Pull request merged**
