### PR TITLE
Remove all listeners when .off gets called without a type

### LINKED ISSUE #70: [question] off(*) behaviour
shouldnt it remove all listeners instead of only listeners attached with `on('*', fn)`? alternatively it would be good to have some `destroy` method to remove all listeners, whatsoever, that could be even achieved with `emitter.off()` (when called without arguments)

### PR DESCRIPTION
**Pull request by Andarist**
fixes #70
```
> npm-run-all --silent clean -p rollup -p minify:* -s docs size

Gzipped Size: 194 B
```

### CODE REVIEW

**Comment by developit** [comment]
Might be worthwhile.  I wonder if this is cheaper than adding a `reset()` function?

**Comment by Andarist** [comment]
Gonna check and report back, clearing solution (`all = Object.create(null)`) is fine though, right?

**Comment by Andarist** [comment]
Adding separate `clear` method:
```
> npm-run-all --silent clean -p rollup -p minify:* -s docs size

Gzipped Size: 197 B
```

Let me know which version do you prefer.

**Comment by olstenlarck** [comment]
I think it is good now. I pretty like that `off` can do few things. It is pretty obvious to me that: a] if there are `type` and `handler` - remove that handler; b] if there is no `handler`, then remove all handlers for that `type`; c] if there is no `type` reset whole thing. Actually as implemented in `dush`.


And btw still can't remember why the hell i did the [removing by comparing strings](https://github.com/tunnckoCore/dush/blob/master/src/index.js#L225-L229), which in turn leads to issues like https://github.com/tunnckoCore/dush/issues/22 :rofl: ... there was a reason to not the `.splice` and `indexOf` ;d

**Comment by Andarist** [comment]
friendly 🏓 is there anything left to do with this PR on my side?

**Comment by Andarist** [comment]
friendly 🏓 😉

**Comment by olstenlarck** [comment]
Probably just merge? There is no automatic release so it won't be published and you can use the master temporary until new eventual release.

**Comment by Andarist** [comment]
@developit friendly 🏓 would love to see this published to ditch our fork 😉

**Comment by developit** [comment]
@Andarist hey, sorry for the delay here.  One issue I can see with this:

If someone passes in a custom `all` object, it'll be overwritten when `off()` is called:

```js
const myEvents = {};
const events = mitt(myEvents);
events.off();
events.on('foo', () => {});
myEvents.foo  // undefined
```

**Comment by Andarist** [comment]
Hm, yeah - that's a possible downside of this. We can't fix it without iterating through the `all` object though and that would for sure exceed the byte budget for mitt. 

OTOH I doubt there are many people relaying on `all` argument (although I'm one of them 🤣 - but I use it to implement `.off` on my own, so this PR would alleviate the issue for me).

Hard to tell what's best here - how useful `all` argument in reality is? What kind of use cases does it cover? 

Ultimately it's your call here 😉

**Comment by developit** [comment]
lol that was my thought too - "oh, people don't use this... except me lol".  Also there seem to have been a fair number of PR's that indicate people are relying on `all`.  I wonder.... how big would this be if we iterated?  It could be gzipped down to very little maybe..

**Comment by Andarist** [comment]
`.all` property seems to me like a more clunky solution - might be a personal preference though.

I've tried deleting all properties:
- with for-in = 214B
- Object.keys + forEach = 214B
- Object.keys + map = 208B

Maybe you could try to squeeze extra bytes out of it as you are expert in this area, but unfortunately I don't have any more ides how to do that 😢

**Comment by jaylinski** [comment]
@Andarist @developit I implemented two ways to fix this:

1. Expose the `all` property: #105 
2. Add a `clear()` function: #104 

Would be nice to get some feedback on this.

**Comment by developit** [comment]
This was implemented in #124 and released in 3.0.0.

**Pull request closed without merging**
