### PR TITLE
Added .npmignore to save some bytes on download

### PR DESCRIPTION
**Pull request by gs-akhan**
Title says it all..

:)

### CODE REVIEW

**Comment by charlike** [comment]
That's pretty weird. Why it even includes it in the package, when it is nowhere defined - it's not in the `files` array? Hm.

**Comment by thiamsantos** [comment]
@gs-akhan Actually the tests [are already not included](https://unpkg.com/mitt@1.1.2/) in the package. So you do not need to add the  `.npmignore`.

**Comment by charlike** [comment]
That's why was thinking, `npmingore` by default uses `gitignore` if exist, so. Even if not that, when paths are not include in `files` or through `main` somehow, they don't get into it, only very important files like LICENSE.

**Comment by gs-akhan** [comment]
Oh ok. My bad..

**Pull request closed without merging**
