### PR TITLE
Fixes #9: use Object.create(null) over {}

### LINKED ISSUE #9: Restrictions for the event name
This code will produce an exception:

```js
const mitt = require("mitt")

const emitter = mitt()

emitter.on('constructor', e => console.log(1))
emitter.emit('constructor', {})
```

You may want to filter all those native methods out, or use a different approach of collecting the events.

### PR DESCRIPTION
**Pull request by agudulin**
Avoid object props inheritance.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
:+1:

**Comment by bfred-it** [comment]
I think the new test still passes even without the change:

```js
const all = {}
all['constructor'] = []
console.log(all['constructor']); // []
``

**Comment by developit** [comment]
Really want to merge this, but I can't seem to get it inside the 200b budget.  Current work to get filesize down is here:
https://github.com/developit/mitt/commit/3a675c7e5a5f7a9a629b59a9dd6e753c6393b36d

Let me know if you have any ideas 😇

**Comment by tunnckoCore** [comment]
it can just be 210 or even 212 because 1) it will include most prs, 2) is fancy, 3) still impressive as and small as 200.

**Comment by bfred-it** [comment]
While I'm all for nano modules (all my packages have a size badge) it's best not to get stuck on the number at the expense of quality.

**Comment by tunnckoCore** [comment]
@bfred-it yea.

@developit one more point is that mentioned commit it is duplicate code and kind of ugly.

**Comment by developit** [comment]
FWIW, I stopped using Moment because it grew too large for me to justify.  I use `date-fns` now.

**Pull request merged**
