### PR TITLE
make on() to return unsubscribe function

### PR DESCRIPTION
**Pull request by mikhail-angelov**
It will be good if on() function returns unsubscribe function

### CODE REVIEW

**Comment by developit** [comment]
Love the idea! Need to figure out a way to keep this under 200b though ;)

**Comment by mjackson** [comment]
Save some space by removing the `off` method?

**Comment by developit** [comment]
That'd break compat with EventEmitter though.  I had wondered if `bind()` would be shorter.

**Comment by loopmode** [comment]
Renaming :) list -> l, type -> t

**Comment by developit** [comment]
@loopmode that's currently done via Uglify as a build step - the 200b size cap we're tracking is actually on the [ES3 output](https://unpkg.com/mitt@1.0.0/dist/mitt.js).

**Comment by mjackson** [comment]
@developit Doesn't seem like compat is that important, is it? node's `EventEmitter` API doesn't even have `off`. They use `removeListener` instead.

**Comment by developit** [comment]
True, I always forget that. I was using WildEmitter prior to writing this, which has `on`/`off`. Touché 😉

**Comment by tunnckoCore** [comment]
@mjackson yea, but it is well-known convention and is feels more natural than returning unsubs from `on`

**Comment by developit** [comment]
I've done both and would love to support both if we can squeeze it in.  The bind technique _should_ make it pretty cheap 👍

**Comment by mikhail-angelov** [comment]
I've tried different implementation to reduce size of final lib, but no luck, I'm getting 38 bites more.
Look's like this initial statement (200b) is too strong since initial version was about this size. :(

**Comment by svincent** [comment]
Here's a technique for manually creating an unsubscribe function.

```js
// Manually bound unsubscribe function
let e = mitt();
function handler() {}
e.on('foo', e);
let unsub = e.off.bind(e, 'foo', handler);
```

**Comment by ajoslin** [comment]
I'm getting 203b for this, though I'm unsure if I'm counting bytes right.

I copied the following then ran  `pbpaste | uglifyjs | gzip -c | wc -c` and got 203.

- Remove all named functions
- Only assign `all[type]` in `on`, it's only needed there.
- Use a slightly shorter assignment for all[type] (no parens needed)
- Don't use Object.create(null), just empty obj
- Return bounded splice from on.

```js
module.exports = function (all) {
  all = all || {};
  return {
    on: function (type, handler) {
      var arr = all[type] = all[type] || [];
      return arr.splice.bind(arr, arr.push(handler) - 1, 1);
    },
    off: function (type, handler) {
      var arr = all[type] || [];
      arr.splice(arr.indexOf(handler) >>> 0, 1);
    },
    emit: function (type, event) {
      (all[type] || []).map(function (handler) { handler(event) });
      (all['*'] || []).map(function (handler) { handler(type, event) });
    }
  };
}
```

**Comment by developit** [comment]
closing in favor of #42

**Pull request closed without merging**
